=== johnny136/XML_semestralka/jan_kladivko.xsd
<?xml version='1.0' encoding='UTF-8' ?> 

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:element name="realitni_portal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="byt" type="byt" maxOccurs="unbounded"/>
                <xs:element name="dum" type="dum" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
                    <xs:complexType name="byt">
                        <xs:sequence>
                            <xs:element name="stav_budovy" type="xs:string"/>
                            <xs:element name="balkon">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="plocha" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="stav_bytu" type="xs:string"/>
                            <xs:element name="vytah">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ano"/>
                                        <xs:enumeration value="ne"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="poschodi" type="xs:string" />
                            <xs:element name="specifikace" type="spc"/>
                        </xs:sequence>
                    </xs:complexType>

                    <xs:complexType name="dum">
                        <xs:sequence>
                            <xs:element name="zastavena_plocha" type="xs:string"/>
                            <xs:element name="plocha_parcely" type="xs:string"/>
                            <xs:element name="oploceni">
                                <xs:simpleType>
                                     <xs:restriction base="xs:string">
                                        <xs:enumeration value="ano"/>
                                        <xs:enumeration value="ne"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sklep">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ano"/>
                                        <xs:enumeration value="ne"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="podkrovi">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="ano"/>
                                        <xs:enumeration value="ne"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="zahrada">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="velikost" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="stav_domu" type="xs:string"/>
                            <xs:element name="specifikace" type="spc"/>    
                        </xs:sequence>
                    </xs:complexType>

        <xs:complexType name="spc">
            <xs:sequence>
                <xs:element name="cislo_zakazky">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:length value="9"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="adresa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="mesto" type="xs:string" />
                            <xs:element name="obec" type="xs:string" />
                            <xs:element name="ulice">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="cislo_popisne" type="xs:string" />
                                            <xs:attribute name="cislo_orientacni" type="xs:string" />
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="podlazi_budovy" type="xs:string" />
                <xs:element name="konstrukce_budovy" type="xs:string" />
                <xs:element name="uzitna_plocha" type="xs:string" />
                <xs:element type="xs:string" name="vybavenost"/>
                <xs:element name="parkovani">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="pocet_mist" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="mistnosti" type="xs:string"/>
                <xs:element name="socialni_zarizeni">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="ano"/>
                            <xs:enumeration value="ne"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="lokalita" type="xs:string"/>
                <xs:element name="dopravni_dostupnost" type="xs:string"/>
                <xs:element name="obcanska_vybavenost" type="xs:string"/>
                <xs:element name="ihned_k_dispozici" type="xs:string"/>
                <xs:element name="zdroj_elektriny" type="xs:string"/>
                <xs:element name="vodni_zdroj" type="xs:string"/>
                <xs:element name="odpad" type="xs:string"/>
                <xs:element name="topeni" type="xs:string"/>
                <xs:element name="plyn" type="xs:string"/>
                <xs:element name="telefon" type="xs:string"/>
                <xs:element name="internet" type="xs:string"/>
                <xs:element name="energeticka_narocnost">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="trida" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cena">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="mena">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:string">
                                            <xs:enumeration value="CZK"/>
                                            <xs:enumeration value="EUR"/>
                                        </xs:restriction>
                                    </xs:simpleType>

                                </xs:attribute>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="cena_za_metrCtverecni" type="xs:string"/>
                <xs:element name="provize_v_cene">
                    <xs:complexType>
                        <xs:simpleContent>
                            <xs:extension base="xs:string">
                                <xs:attribute name="procent" type="xs:string"/>
                            </xs:extension>
                        </xs:simpleContent>
                    </xs:complexType>
                </xs:element>
                <xs:element name="moznost_hypoteky">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="ano"/>
                            <xs:enumeration value="ne"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="prodejce">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="jmeno" type="xs:string"/>
                            <xs:element name="firma" type="xs:string"/>
                            <xs:element name="hodnoceni" type="xs:string"/>
                            <xs:element name="kontakt">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="telefon">
                                                <xs:simpleType>
                                                    <xs:restriction base="xs:string">
                                                        <xs:length value="9"/>
                                                    </xs:restriction>
                                                </xs:simpleType>
                                            </xs:attribute>
                                            <xs:attribute name="email" type="xs:string"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                 </xs:element>         
            </xs:sequence>
        </xs:complexType> 
</xs:schema>

=== johnny136/XML_semestralka/jan_kladivko.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="jan_kladivko.xsl"?>
<realitni_portal xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jan_kladivko.xsd">
    <byt>
        <stav_budovy>dobry stav</stav_budovy>
        <balkon plocha="0m^2">ne</balkon>
        <stav_bytu>dobry stav</stav_bytu>
        <vytah>ne</vytah>
        <poschodi>prizemi</poschodi>
        <specifikace>
            <cislo_zakazky>4698-SDBQ</cislo_zakazky>
            <adresa>
                <mesto>Praha 2</mesto>
                <obec>Nove Mesto</obec>
                <ulice cislo_popisne="1814" cislo_orientacni="5">Tyrsova</ulice>
            </adresa>
            <podlazi_budovy>6</podlazi_budovy>
            <konstrukce_budovy>cihlova</konstrukce_budovy>
            <uzitna_plocha>102m^2</uzitna_plocha>
            <vybavenost>zarizeno</vybavenost>
            <parkovani pocet_mist="MZ">modra zona</parkovani>
            <mistnosti>3+1</mistnosti>
            <socialni_zarizeni>ano</socialni_zarizeni>
            <lokalita>rusna cast</lokalita>
            <dopravni_dostupnost>Auto, MHD</dopravni_dostupnost>
            <obcanska_vybavenost>Restaurace, Obchod, Kulturni zarizeni</obcanska_vybavenost>
            <ihned_k_dispozici>ano</ihned_k_dispozici>
            <zdroj_elektriny>230V</zdroj_elektriny>
            <vodni_zdroj>verejny</vodni_zdroj>
            <odpad>verejny odpad</odpad>
            <topeni>ustredni - elektrina</topeni>
            <plyn>verejny privod</plyn>
            <telefon>pripojen</telefon>
            <internet>pripojen</internet>
            <energeticka_narocnost trida="G">Mimoradne nehospodarna</energeticka_narocnost>
            <cena mena="CZK">9250000</cena>
            <cena_za_metrCtverecni>90686</cena_za_metrCtverecni>
            <provize_v_cene procent="10">ano</provize_v_cene>
            <moznost_hypoteky>ano</moznost_hypoteky>
            <prodejce>
                <jmeno>Stanislav Bozek</jmeno>
                <firma>Reality 11</firma>
                <hodnoceni>98%</hodnoceni>
                <kontakt telefon="728332641" email="stanislav.bozek@reality11.cz"/>
            </prodejce>
        </specifikace>
    </byt>
    <byt>
        <stav_budovy>po rekonstrukci</stav_budovy>
        <balkon plocha="10m^2">ano</balkon>
        <stav_bytu>novy</stav_bytu>
        <vytah>ano</vytah>
        <poschodi>2.</poschodi>
        <specifikace>
            <cislo_zakazky>4698-SDBQ</cislo_zakazky>
            <adresa>
                <mesto>Praha 8</mesto>
                <obec>Liben</obec>
                <ulice cislo_popisne="1475" cislo_orientacni="180">Sokolovska</ulice>
            </adresa>
            <podlazi_budovy>8</podlazi_budovy>
            <konstrukce_budovy>zdena</konstrukce_budovy>
            <uzitna_plocha>63m^2</uzitna_plocha>
            <vybavenost>zarizeno</vybavenost>
            <parkovani pocet_mist="MZ">modra zona</parkovani>
            <mistnosti>2+kk</mistnosti>
            <socialni_zarizeni>ano</socialni_zarizeni>
            <lokalita>klidna cast</lokalita>
            <dopravni_dostupnost>Auto, MHD</dopravni_dostupnost>
            <obcanska_vybavenost>skola, skolka, Restaurace, Obchod, Kulturni zarizeni</obcanska_vybavenost>
            <ihned_k_dispozici>ano</ihned_k_dispozici>
            <zdroj_elektriny>230V/400V</zdroj_elektriny>
            <vodni_zdroj>verejny</vodni_zdroj>
            <odpad>verejna kanalizace</odpad>
            <topeni>ustredni - dalkove</topeni>
            <plyn>verejny privod</plyn>
            <telefon>pripojen</telefon>
            <internet>pripojen</internet>
            <energeticka_narocnost trida="B">usporna</energeticka_narocnost>
            <cena mena="CZK">5640000</cena>
            <cena_za_metrCtverecni>89524</cena_za_metrCtverecni>
            <provize_v_cene procent="15">ano</provize_v_cene>
            <moznost_hypoteky>ano</moznost_hypoteky>
            <prodejce>
                <jmeno>Katerina Lepsova</jmeno>
                <firma>Duna House</firma>
                <hodnoceni>91%</hodnoceni>
                <kontakt telefon="606566222" email="k.lepsova@dunahouse.com"/>
            </prodejce>
        </specifikace>
    </byt>
    <dum>
        <zastavena_plocha>376m^2</zastavena_plocha>
        <plocha_parcely>7803m^2</plocha_parcely>
        <oploceni>ano</oploceni>
        <sklep>ano</sklep>
        <podkrovi>ano</podkrovi>
        <zahrada velikost="7427m^2">ano</zahrada>
        <stav_domu>dobry stav</stav_domu>
        <specifikace>
            <cislo_zakazky>7894-POLQ</cislo_zakazky>
            <adresa>
                <mesto>Velke Mezirici</mesto>
                <obec>zdar nad Sazavou</obec>
                <ulice cislo_popisne="2010" cislo_orientacni="-">Nad Lal≈Øvkou</ulice>
            </adresa>
            <podlazi_budovy>3</podlazi_budovy>
            <konstrukce_budovy>cihlova</konstrukce_budovy>
            <uzitna_plocha>350m^2</uzitna_plocha>
            <vybavenost>castecne zarizeno</vybavenost>
            <parkovani pocet_mist="6">garaz</parkovani>
            <mistnosti>5+1</mistnosti>
            <socialni_zarizeni>ano</socialni_zarizeni>
            <lokalita>klidna cast</lokalita>
            <dopravni_dostupnost>Auto, Dalnice, I. trida, II. trida, Vlak</dopravni_dostupnost>
            <obcanska_vybavenost>skola, skolka, Nakupni centrum, Restaurace, Posta, Mistni urad, Lekar, Kulturni zarizeni, Koupaliste</obcanska_vybavenost>
            <ihned_k_dispozici>ne</ihned_k_dispozici>
            <zdroj_elektriny>230V verejny</zdroj_elektriny>
            <vodni_zdroj>verejny</vodni_zdroj>
            <odpad>verejny odpad</odpad>
            <topeni>ustredni - plynove</topeni>
            <plyn>zaveden</plyn>
            <telefon>zaveden</telefon>
            <internet>zaveden</internet>
            <energeticka_narocnost trida="C">usporna</energeticka_narocnost>
            <cena mena="CZK">15000000</cena>
            <cena_za_metrCtverecni>39894</cena_za_metrCtverecni>
            <provize_v_cene procent="0">ne</provize_v_cene>
            <moznost_hypoteky>ano</moznost_hypoteky>
            <prodejce>
                <jmeno>Jiri Prokes</jmeno>
                <firma>RK Michalek and Partners</firma>
                <hodnoceni>86%</hodnoceni>
                <kontakt telefon="724936711" email="prokes.jiri@mandp.cz"/>
            </prodejce>
        </specifikace>
    </dum>
    <dum>
        <zastavena_plocha>152m^2</zastavena_plocha>
        <plocha_parcely>822m^2</plocha_parcely>
        <oploceni>ano</oploceni>
        <sklep>ano</sklep>
        <podkrovi>ne</podkrovi>
        <zahrada velikost="670m^2">ano</zahrada>
        <stav_domu>dobry stav</stav_domu>
        <specifikace>
            <cislo_zakazky>9312-ZYXO</cislo_zakazky>
            <adresa>
                <mesto>Nova Ves</mesto>
                <obec>Melnik</obec>
                <ulice cislo_popisne="48" cislo_orientacni="3">Nova Ves</ulice>
            </adresa>
            <podlazi_budovy>3</podlazi_budovy>
            <konstrukce_budovy>zdena</konstrukce_budovy>
            <uzitna_plocha>440m^2</uzitna_plocha>
            <vybavenost>castecne zarizeno</vybavenost>
            <parkovani pocet_mist="2">garaz</parkovani>
            <mistnosti>10+21</mistnosti>
            <socialni_zarizeni>ano</socialni_zarizeni>
            <lokalita>klidna cast</lokalita>
            <dopravni_dostupnost>Auto, Autobus, Dalnice, I. trida, II. trida</dopravni_dostupnost>
            <obcanska_vybavenost>skola, skolka, Obchod, Restaurace, Posta, Mistni urad, Lekar, Kulturni zarizeni</obcanska_vybavenost>
            <ihned_k_dispozici>ano</ihned_k_dispozici>
            <zdroj_elektriny>230V verejny</zdroj_elektriny>
            <vodni_zdroj>verejny</vodni_zdroj>
            <odpad>septik</odpad>
            <topeni>ustredni - tuha paliva</topeni>
            <plyn>zaveden</plyn>
            <telefon>zaveden</telefon>
            <internet>zaveden</internet>
            <energeticka_narocnost trida="B">usporna</energeticka_narocnost>
            <cena mena="CZK">13990000</cena>
            <cena_za_metrCtverecni>31795</cena_za_metrCtverecni>
            <provize_v_cene procent="0">ne</provize_v_cene>
            <moznost_hypoteky>ano</moznost_hypoteky>
            <prodejce>
                <jmeno>Petr Hlavaty</jmeno>
                <firma>M and M reality holding a.s.</firma>
                <hodnoceni>80%</hodnoceni>
                <kontakt telefon="800949711" email="petr.hlavaty@mmreality.cz"/>
            </prodejce>
        </specifikace>
    </dum>
    <dum>
        <zastavena_plocha>132m^2</zastavena_plocha>
        <plocha_parcely>332m^2</plocha_parcely>
        <oploceni>ano</oploceni>
        <sklep>ano</sklep>
        <podkrovi>ne</podkrovi>
        <zahrada velikost="190m^2">ano</zahrada>
        <stav_domu>dobry stav</stav_domu>
        <specifikace>
            <cislo_zakazky>1346-AZYO</cislo_zakazky>
            <adresa>
                <mesto>Praha 9</mesto>
                <obec>Horni Pocernice</obec>
                <ulice cislo_popisne="203" cislo_orientacni="94">Trebesovska</ulice>
            </adresa>
            <podlazi_budovy>2</podlazi_budovy>
            <konstrukce_budovy>cihlova</konstrukce_budovy>
            <uzitna_plocha>230m^2</uzitna_plocha>
            <vybavenost>nezarizeno</vybavenost>
            <parkovani pocet_mist="2">prijezdova cesta</parkovani>
            <mistnosti>4kk</mistnosti>
            <socialni_zarizeni>ano</socialni_zarizeni>
            <lokalita>rusna cast</lokalita>
            <dopravni_dostupnost>Auto, Dalnice, I. trida, Vlak, MHD</dopravni_dostupnost>
            <obcanska_vybavenost>skola, skolka, Obchod, Restaurace, Posta, Mistni urad, Lekar, Kulturni zarizeni</obcanska_vybavenost>
            <ihned_k_dispozici>ne</ihned_k_dispozici>
            <zdroj_elektriny>230V verejny</zdroj_elektriny>
